### ISSUE TITLE
social media buttons

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#1]
Sommige buttons gaan open in een nieuwe tabblad, andere in een nieuw venster en facebook gaat bij mij niet open. Missschien allemaal openen in een nieuw tabblad?

**Comment by JorisLambrechts** [comment]
In orde na opnieuw selecter van de facebook optie in admin. Die code zit bij addthis, dus als het niet werkt kunnen we er weinig aan doen, maar voorlopig werkt het dus weer.

**Comment by roxannewyns** [comment]
bij mij nog steeds zelfde resultaat, ook in explorer getest.

**Comment by JorisLambrechts** [comment]
Bij exhibits wil het bij mij ook nog niet lukken. Items en collecties wel, ik zoek het verder uit.
