### ISSUE TITLE
opmerking goedkeuring

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#10]
Ik krijg een foutmelding bij poging aanpassing status in admin.

![image](https://user-images.githubusercontent.com/3798589/34214443-c8fafdf4-e5a2-11e7-83f4-fb3374c13953.png)

**Comment by roxannewyns** [comment]
Kan je me nog eens laten weten waar de email adressen van personen die een boodschap achter laten worden opgeslagen? Kadoc zou in sommige gevallen de personen willen kunnen contacteren.

**Comment by JorisLambrechts** [comment]
Akismet is de automatische spamfilter. Dus spamgerelateerde controles gaan altijd eerst naar die api, maar daar moeten we dus weer een proxy instellen wat niet evident is omdat dat het weer een functie van Zend die niet veel documentatie heeft.

Naeem gebruikt de filter niet bij espace dus ik heb het voorlopig maar uitgezet. Recaptcha staat ook op dus normaal hoeft die akismet niet.

**Comment by roxannewyns** [comment]
best uitzetten dan zeker. ik krijg nu een andere melding
![image](https://user-images.githubusercontent.com/3798589/34667912-5cad5a8e-f46b-11e7-81da-207a5373a42e.png)

**Comment by JorisLambrechts** [comment]
Opgelost. Deze 2 comments stonden nog als spam in de databank waardoor er weer naar akismet gezocht werd.
