### ISSUE TITLE
Tentoonstelling - overzichtspagina sortering en weergave

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#13]
meest recente tentoonstelling bovenaan plaatsen
favorieten ook een blauw kader geven (idem aan items en collecties)
filter toevoegen 'Aanbevolen'

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Kadoc-omeka/commit/934aedb42b3330174ca53d3509a0b72140e1d2a8
