### ISSUE TITLE
banner afmeting

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#14]
Kan je de meest gepast banner afmeting nog eens doorgeven.

**Comment by JorisLambrechts** [comment]
breedte: tussen 2000px en 1400px
hoogte: minstens 500px

De banner wordt over de hele breedte van scherm getoond (op mijn scherm is dat 1905px). Dus een afbeelding van 1400px wordt vergroot tot 1905px en is dan wat minder scherp, dat is geen ramp aangezien het een achtergrond is maar met 2000px zit je wel wat comfortabeler natuurlijk (hoger zou ik niet gaan omdat de afbeelding dan te zwaar wordt).

De huidige bannerafbeelding op de homepage is trouwens maar 1265px op 428px en ziet er ook nog degelijk uit.
