### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#15]
Als je items via csv importeerd moet je een link meegeven naar beelden die op een weblocatie toegankelijk zijn. Zijn er ook andere manieren, e.g. voor materiaal dat op een harde schijf of PC staat? Er is wel die drop-box plugin, maar na dit snel te lezen lijkt het me dat je dan voor elke file die je importeerd een item aanmaakt.

**Comment by JorisLambrechts** [comment]
Je kan kiezen welke file een item moet worden, files die je niet aanvinkt worden geen items. Je kan wel niet automatisch meerdere files in 1 item omzetten, je kan wel manueel files toevoegen aan een al bestaand item. Dat is misschien nog haalbaar als het over kleine hoeveelheden items/files gaat.

Bij de dropbox-plugin moet je de files ook wel eerst op de webserver zetten, dus je kan dan evengoed de csv-import gebruiken.
