### ISSUE TITLE
csv import blijkft op queued staan

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#16]
Ik heb de indruk dat de csv op queued blijft staan. Zie test file in toegevoegde zip. 

![image](https://user-images.githubusercontent.com/3798589/34676259-87cddee8-f48c-11e7-9d48-95c821f5173d.png)

[csv import voorbeeld.zip](https://github.com/libis/Kadoc-omeka/files/1611908/csv.import.voorbeeld.zip)

**Comment by JorisLambrechts** [comment]
dit is een probleem met config.ini denk ik ik vergelijk het even met flandrica

**Comment by JorisLambrechts** [comment]
Het lukt nu, heb in admin ook 'Schakel validatie bij bestandsupload uit' moeten aanvinken. Ik zoek nog verder uit of een achtergrondproces ook mogelijk is.
