### ISSUE TITLE
zoekresultaten overzicht erfgoed in de kijker - titel item

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#18]
/items/browse?tags=Erfgoed+in+de+kijker

Als je over het object gaat en je wilt de tekst aanklikken, verdwijnt deze (omwille van kleur vermoed ik). Daarnaast had ik begrepen dat ze de hoofd en ondertitel van het verhaal wilden zien in de zoekresultaten preview.

![image](https://user-images.githubusercontent.com/3798589/37412133-9c93926e-27a4-11e8-8166-4785476d39ff.png)

**Comment by JorisLambrechts** [comment]
Dit is in orde, ik toon de gewone titel als de verhaal titel nog niet is ingevuld.

Er zijn nieuwe velden toegevoegd die nog ingevuld moeten worden:
Verhaal titel, Verhaal ondertitel, Story title, Story subtitle
