### ISSUE TITLE
thumbnails naast elkaar tonen?

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#3]
Misschien beter om ze naast elkaar te plaatsen? Of is hier een reden voor?

![image](https://user-images.githubusercontent.com/3798589/34211190-9c2b93f6-e598-11e7-9e0e-68f5fcd5f514.png)

**Comment by JorisLambrechts** [comment]
Moeten de afbeeldingen ook een lightbox krijgen of gewoon thumbnails met een link naar de grotere versie? Een caroussel kan ook natuurlijk.

**Comment by roxannewyns** [comment]
lightbox zou mooi zijn. caroussel lijkt me niet nodig
