### ISSUE TITLE
2de tentoonstelling wordt niet getoond

### ISSUE THREAD

**Issue by roxannewyns** [libis/Kadoc-omeka#6]
ik heb een 2de testtentoonstelling gemaakt, maar deze verschijnt niet op de overzichtspagina.

**Comment by JorisLambrechts** [comment]
moest op nl_be gezet worden (via admin->MultiLanguage content)

**Comment by roxannewyns** [comment]
OK. Hoe komt die ene tentoonstelling bovenaan te staan? De mijne is recenter en staat als favoriet

**Comment by JorisLambrechts** [comment]
ik moet de sortering nog aanpassen, dacht dat het standaard op meest recente stond maar dat is dus niet het geval
